"""Inventory template constructs that require CSP ``'unsafe-inline'``.

This is intentionally a small static scanner rather than an HTML parser: Jinja
templates are not always valid standalone HTML, while the constructs we prohibit
have simple, stable spellings. The scanner is used both from pytest and as a local
progress report during the CSP migration.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Dict, Iterable, List


ROOT = Path(__file__).resolve().parents[1]
TEMPLATES_DIR = ROOT / "templates"
STATIC_DIR = ROOT / "static"

HTML_COMMENT_RE = re.compile(r"""<!--.*?-->""", re.DOTALL)
JINJA_COMMENT_RE = re.compile(r"""\{#.*?#\}""", re.DOTALL)
EVENT_HANDLER_RE = re.compile(r"""\son[a-z][a-z0-9:_-]*\s*=""", re.IGNORECASE)
STYLE_ATTRIBUTE_RE = re.compile(r"""\sstyle\s*=""", re.IGNORECASE)
STYLE_BLOCK_RE = re.compile(r"""<style\b[^>]*>""", re.IGNORECASE)
SCRIPT_OPEN_RE = re.compile(r"""<script\b(?P<attrs>[^>]*)>""", re.IGNORECASE)
SRC_ATTRIBUTE_RE = re.compile(r"""\ssrc\s*=""", re.IGNORECASE)
INERT_SCRIPT_TYPE_RE = re.compile(
    r"""\stype\s*=\s*(?:["'](?:application/json|application/ld\+json)["']"""
    r"""|(?:application/json|application/ld\+json)(?=\s|$))""",
    re.IGNORECASE,
)
JAVASCRIPT_URL_RE = re.compile(
    r"""\s(?:href|src|action|formaction|xlink:href)\s*=\s*"""
    r"""(?:"\s*javascript:|'\s*javascript:|javascript:)""",
    re.IGNORECASE,
)
GENERATED_EVENT_HANDLER_RE = re.compile(r"""\son[a-z][a-z0-9:_-]*\s*=""", re.IGNORECASE)
GENERATED_STYLE_ATTRIBUTE_RE = re.compile(r"""\sstyle\s*=""", re.IGNORECASE)
GENERATED_JAVASCRIPT_URL_RE = re.compile(r"""javascript\s*:""", re.IGNORECASE)

CATEGORIES = (
    "event_handlers",
    "executable_inline_scripts",
    "javascript_urls",
    "style_blocks",
    "style_attributes",
)


# Email bodies, not pages. They are never served to a browser, so no Content
# Security Policy applies to them — and inline style attributes are not debt
# there but a hard requirement: Gmail and Outlook strip <style> blocks and
# external stylesheets, so a mail template that obeyed CSP would arrive
# unstyled. Excluded from the inventory rather than baselined, because the
# count should be free to grow as more emails are added.
EXCLUDED_DIRS = ("email",)


def _template_paths(directory: Path = TEMPLATES_DIR) -> Iterable[Path]:
    return sorted(
        path for path in directory.rglob("*.html")
        if not set(path.relative_to(directory).parts[:-1]) & set(EXCLUDED_DIRS)
    )


def scan_file(path: Path) -> Dict[str, int]:
    text = path.read_text(encoding="utf-8")
    text = HTML_COMMENT_RE.sub("", text)
    text = JINJA_COMMENT_RE.sub("", text)
    inline_scripts = 0
    for match in SCRIPT_OPEN_RE.finditer(text):
        attrs = match.group("attrs")
        if SRC_ATTRIBUTE_RE.search(attrs) or INERT_SCRIPT_TYPE_RE.search(attrs):
            continue
        inline_scripts += 1
    return {
        "event_handlers": len(EVENT_HANDLER_RE.findall(text)),
        "executable_inline_scripts": inline_scripts,
        "javascript_urls": len(JAVASCRIPT_URL_RE.findall(text)),
        "style_blocks": len(STYLE_BLOCK_RE.findall(text)),
        "style_attributes": len(STYLE_ATTRIBUTE_RE.findall(text)),
    }


def scan_templates(directory: Path = TEMPLATES_DIR) -> Dict[str, Dict[str, int]]:
    inventory: Dict[str, Dict[str, int]] = {}
    for path in _template_paths(directory):
        counts = scan_file(path)
        if any(counts.values()):
            inventory[path.relative_to(directory).as_posix()] = counts
    return inventory


def totals(inventory: Dict[str, Dict[str, int]]) -> Dict[str, int]:
    return {
        category: sum(row[category] for row in inventory.values())
        for category in CATEGORIES
    }


def violations(inventory: Dict[str, Dict[str, int]]) -> List[str]:
    found = []
    for template, counts in inventory.items():
        for category, count in counts.items():
            if count:
                found.append(f"{template}: {category}={count}")
    return found


def scan_generated_markup(directory: Path = STATIC_DIR) -> Dict[str, Dict[str, int]]:
    """Find CSP-relevant HTML fragments generated by first-party JavaScript."""
    inventory: Dict[str, Dict[str, int]] = {}
    for path in sorted(directory.glob("*.js")):
        text = path.read_text(encoding="utf-8")
        counts = {
            "event_handlers": len(GENERATED_EVENT_HANDLER_RE.findall(text)),
            "style_attributes": len(GENERATED_STYLE_ATTRIBUTE_RE.findall(text)),
            "javascript_urls": len(GENERATED_JAVASCRIPT_URL_RE.findall(text)),
        }
        if any(counts.values()):
            inventory[path.name] = counts
    return inventory


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--strict",
        action="store_true",
        help="exit non-zero if any inline executable code or styling remains",
    )
    parser.add_argument("--json", action="store_true", help="print the full inventory as JSON")
    args = parser.parse_args()

    inventory = scan_templates()
    generated = scan_generated_markup()
    if args.json:
        print(json.dumps({
            "totals": totals(inventory),
            "templates": inventory,
            "generated_markup": generated,
        }, indent=2))
    else:
        print(json.dumps(totals(inventory), sort_keys=True))
    if args.strict and (violations(inventory) or generated):
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
